### ISSUE TITLE
Error during test run with sample data

### ISSUE THREAD

**Issue by DanParkMDS** [pieterjanvc/seq2mgs#1]
Hi, I recently have been trying to use SEQ2MGS and started by running the setup.sh which notified me that all dependencies (minus sratoolkit for now) have been installed. I then tried to run with the sample data, using the command:

bash seq2mgs.sh -i seq2mgs/dataAndScripts/testData/input.csv -o test.fastq.gz

which got to the point where it was trying to extract reads from isolate_1.fastq.gz and isolate_2.fastq.gz. However, it then returned this error:

--- ERROR LINE 181 ---

Error in system(sprintf("rename.sh in=%s/partial.fastq.gz out=%s/tempFile%i_partial.fastq.gz ow=t prefix=fileId%i_partial_read 2>&1",  : 
  error in running command

I have been trying to find a way to debug this but have had no luck. Is there something I am doing wrong?

**Comment by pieterjanvc** [comment]
Hello,

Do you get the same issue when you run the following:
```
setup.sh -t
```
The -t command runs the test in a pre-configured way.

Let me know if this works
PJ

**Comment by DanParkMDS** [comment]
Hi, 

Yes, I just tried that command (bash setup.sh -t) and got the following output:

2) Test mixing metagenome... 
--- ERROR LINE 181 ---

Error in system(sprintf("rename.sh in=%s/partial.fastq.gz out=%s/tempFile%i_partial.fastq.gz ow=t prefix=fileId%i_partial_read 2>&1",  : 
  error in running command
Calls: tryCatch -> tryCatchList -> system
In addition: Warning messages:
1: Unknown or uninitialised column: `getFromSRA`. 
2: Unknown or uninitialised column: `getFromSRA`. 
Execution halted

--- ERROR LINE 163 ---

Error in system(sprintf("rename.sh in=%s/partial.fastq.gz out=%s/tempFile%i_partial.fastq.gz ow=t prefix=fileId%i_partial_read 2>&1",  : 

which largely appears to be the same (or very similar) issue. Using grep for the error message on the files within the repo, it seems as though the error originates within the seq2mgs.R file

**Comment by pieterjanvc** [comment]
Hello,

I tried to run the test on my side again after doing a fresh install and making sure I had all the latest tools installed and I do not get the error you are having.

Judging by the message, it seems that the issue arises when running the 'rename.sh' script from the bbmap package. Can you verify that it is in your $PATH by running
```
>  rename.sh

Written by Brian Bushnell
Last modified April 1, 2020
...
```
Let me know if you get the same output. If not, check if bbmap is correctly installed and the scripts are accessible in $PATH (with no conflicts with other scripts with same name).

Thanks

**Comment by DanParkMDS** [comment]
Hi, 

That worked perfectly! After modifying the PATH variable to ensure it was pointed to bbmap's directory, everything was able to run without issue. Thank you for the help!
